object Compose {
    const val composeVersion = "1.3.1"
    const val composeCompilerVersion = "1.3.2"
    private const val runtimeLivedataVersion = "1.3.1"
    private const val navigationVersion = "2.5.2"
    private const val activityComposeVersion = "1.6.0"
    private const val hiltNavigationComposeVersion = "1.0.0-beta01"
    private const val lifecycleVersion = "2.5.1"
    private const val lifecycleRuntimeComposeVersion = "2.6.0-alpha01"
    private const val lottieComposeVersion = "5.2.0"
    private const val composeMaterial3Version = "1.1.0-alpha02"
    const val material = "androidx.compose.material:material:$composeVersion"
    const val ui = "androidx.compose.ui:ui:$composeVersion"
    const val uiFoundation = "androidx.compose.foundation:foundation:$composeVersion"
    const val composeAnimation = "androidx.compose.animation:animation:$composeVersion"
    const val uiToolingPreview = "androidx.compose.ui:ui-tooling-preview:$composeVersion"
    const val uiTooling = "androidx.compose.ui:ui-tooling:$composeVersion"
    const val runtime = "androidx.compose.runtime:runtime:$composeVersion"
    const val runtimeRxjava2 = "androidx.compose.runtime:runtime-rxjava2:$composeVersion"
    const val runtime_livedata = "androidx.compose.runtime:runtime-livedata:$runtimeLivedataVersion"
    const val navigation = "androidx.navigation:navigation-compose:$navigationVersion"
    const val hiltNavigationCompose = "androidx.hilt:hilt-navigation-compose:$hiltNavigationComposeVersion"
    const val activityCompose = "androidx.activity:activity-compose:$activityComposeVersion"
    const val viewModelCompose = "androidx.lifecycle:lifecycle-viewmodel-compose:$lifecycleVersion"
    const val lifecycleRuntimeCompose = "androidx.lifecycle:lifecycle-runtime-compose:$lifecycleRuntimeComposeVersion"
    const val lottieCompose = "com.airbnb.android:lottie-compose:$lottieComposeVersion"
    const val composeMaterial3 = "androidx.compose.material3:material3:$composeMaterial3Version"

}
